version: '3.9'

services:
  host:
    image: host:latest
    container_name: host
    ports:
      - "4000:4000"
    env_file:
      - .env.production
  remote:
    image: remote:latest
    container_name: remote
    ports:
      - "4001:4001"
    env_file:
      - .env.production