worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /opt/homebrew/etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    # HTTP 접속 시 HTTPS (5000 포트)로 리다이렉트
    server {
        listen 80;
        server_name localhost;
        return 301 https://$host:5000$request_uri;
    }

    # HTTPS 서버: 중앙에서 모든 요청을 받아서 각각의 서비스로 프록시
    server {
        listen 5000 ssl;
        server_name localhost;

        ssl_certificate     /Users/netand/Documents/study/nextjs-page-router-test/certificates/STAR.netand.co.kr_crt.pem;
        ssl_certificate_key /Users/netand/Documents/study/nextjs-page-router-test/certificates/STAR.netand.co.kr_key.pem;
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        # /remote 요청: remote 서비스 (Next.js가 포트 4001에서 실행)
       location /remote/ {
            proxy_pass         http://localhost:4001/;
            proxy_http_version 1.1;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection 'upgrade';
            proxy_set_header   Host $host;
            proxy_cache_bypass $http_upgrade;
        }
        # /host 요청: host 서비스 (Next.js가 포트 4000에서 실행)
        location / {
            proxy_pass         http://localhost:4000/;
            proxy_http_version 1.1;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection 'upgrade';
            proxy_set_header   Host $host;
            proxy_cache_bypass $http_upgrade;
        }



    }
}
